name: Practice
version: '1.0'
main: me.illia.practice.Practice
api-version: 1.16


commands:
  setRank:
    description: 'Set rank to player'
    usage: /<command> Player Rank
    permission: default
  openMenu:
    description: 'Open gui menu'
    usage: /<command>
    permission: default
  magicWand:
    description: 'Gives to executor magic wand'
    usage: /<command>
    permission: default
  teleporter:
    description: 'Gives to executor teleporter'
    usage: /<command>
    permission: default
  setprefix:
    description: 'Changes player prefix'
    usage: /<command>
    permission: default
  openPrefixMenu:
    description: 'Open prefix gui'
    usage: /<command> Player Rank
    permission: default
